spring.application.name=api-gateway
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.profiles.active=dev
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=2s
spring.data.mongodb.uri=mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017/technova-api-gateway?authSource=admin
spring.jwt.keys.secret=classpath:key.pem
spring.jwt.keys.public=classpath:public.pem