spring.application.name=api-gateway
server.port=8080
spring.rabbitmq.addresses=amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.initial-interval=2s
spring.data.mongodb.uri=${MONGODB_URI_API_GATEWAY}
spring.jwt.keys.secret=file:/app/keys/key.pem
spring.jwt.keys.public=file:/app/keys/public.pem