apiVersion: apps/v1
kind: Deployment
metadata:
  name: technova-api-gateway
  namespace: technova
  labels:
    app: technova-api-gateway
spec:
  replicas: 3
  selector:
    matchLabels:
      app: technova-api-gateway
  template:
    metadata:
      labels:
        app: technova-api-gateway
    spec:
      containers:
        - name: technova-api-gateway
          image: gwrgwr/technova-api-gateway:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: jwt-public-key-volume
              mountPath: /app/keys/public.pem
              subPath: public.pem
            - name: jwt-private-key-volume
              mountPath: /app/keys/key.pem
              subPath: key.pem
          env:
            - name: MONGODB_URI_API_GATEWAY
              valueFrom:
                secretKeyRef:
                  name: mongodb-api-gateway
                  key: MONGODB_URI_API_GATEWAY
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: RABBITMQ_USER
              valueFrom:
                  secretKeyRef:
                    name: rabbitmq-credentials
                    key: username
            - name: RABBITMQ_PASS
              valueFrom:
                      secretKeyRef:
                        name: rabbitmq-credentials
                        key: password
            - name: RABBITMQ_HOST
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: host
            - name: RABBITMQ_PORT
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: port
      volumes:
        - name: jwt-public-key-volume
          configMap:
            name: jwt-public-key
            items:
              - key: public.pem
                path: public.pem
        - name: jwt-private-key-volume
          secret:
            secretName: jwt-private-key
            items:
              - key: key.pem
                path: key.pem
