apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
  namespace: api-gateway
spec:
  containers:
    - name: api-gateway
      image: gwrgwr/murilo.ramos:api-gateway-22
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: jwt-public-key-volume
          mountPath: /app/keys/public.pem
          subPath: public.pem
        - name: jwt-private-key-volume
          mountPath: /app/keys/key.pem
          subPath: private.pem
  imagePullSecrets:
    - name: dockerhub-credentials
  volumes:
    - name: jwt-public-key-volume
      configMap:
        name: jwt-public-key
    - name: jwt-private-key-volume
      secret:
        secretName: jwt-private-key