apiVersion: v1
kind: Pod
metadata:
  name: api-gateway
spec:
  containers:
    - name: api-gateway
      image: gwrgwr/murilo.ramos:api-gateway-22
      ports:
        - containerPort: 8080
  imagePullSecrets:
    - name: dockerhub-credentials
  volumes:
    - name: jwt-public-key-volume
      configMap:
        name: jwt-public-key
    - name: jwt-private-key-volume
      secret:
        secretName: jwt-private-key